# Generated by Django 4.2.4 on 2023-08-21 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الأسم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(verbose_name='سعر الكشف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(max_length=250, verbose_name='من انا'),
        ),
    ]
