# Generated by Django 4.2.4 on 2023-08-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sluge',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
