# Generated by Django 4.2.4 on 2023-08-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_sluge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان بالتفصيل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور فى'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الموبيل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist_at',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متخصص فى'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نبذة عنك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='وقت الانتظار بالدقائق'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الأسم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='من انا'),
        ),
    ]
